"""
APEX OMNI v9.7.1 — COMMODITY FORGE (trains the commodity meta-labeler)
=====================================================================
The commodity analog of the equity forge's meta-training path. It closes the
last gap: the commodity brain runs heuristic-only until THIS produces a
promoted model — exactly how the equity brain crossed the same boundary.

Zero-divergence design (every load-bearing piece is REUSED, not re-implemented)
------------------------------------------------------------------------------
  • Vault reading:  simulation.replay_real_day.load_day — the SAME loader the
    equity forge uses. Its query carries no token filter, so bidA/askA/by_sec
    already cover every harvested commodity token (futures + option legs).
  • Instruments:    core.instruments.AsOfMapper — the harvester snapshots
    commodity chains daily (write_snapshot writes self._rows, which includes
    the MCX rows), so historical replay resolves commodity chains natively.
  • Side decision:  core.commodity_brain.CommodityHeuristicPolicy over nodes
    built by the SAME StateBuilder.leg_features — the live brain's exact
    signal path, so labels are generated by the policy that will be gated.
  • Barriers/costs: nightly_forge_v9._shaped_barriers, _hold_seconds,
    round_trip_costs — identical first-touch triple-barrier grading.
  • Trainer:        core.meta_gbm.fit_gbm — the SAME purged-day-fold LightGBM
    + weighted-isotonic pipeline (universe-agnostic by interface). Fail-open:
    if lightgbm is absent or CV is too thin it returns None and the commodity
    brain simply STAYS heuristic-only. A missing package can never fake a model.
  • Labels carry AFML uniqueness weights (mean 1/concurrency over the span),
    per commodity — same as equity.

Sample x-vector (MUST match serving; commodity_brain builds the identical x):
  [spot_node(19), atm_ce_node(19), atm_pe_node(19), t/N, kaufman_er,
   capped_mom30, +1 if CE else -1]                                  → 61 dims

Data-gated by design: with an empty/thin commodity vault it logs
"keep harvesting" and writes nothing. COMMODITY_META_MIN_TRAIN gates training;
the artifact goes to MODEL_DIR/commodity_meta.json, which
core.commodity_brain.load_commodity_meta already reads.

  python nightly_commodity_forge.py [--days N]
"""
from __future__ import annotations

import argparse
import json
import math
import sqlite3
import sys
import time
from collections import deque
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))

import config                                             # noqa: E402
from core.market_state import StateBuilder                 # noqa: E402
from core.instruments import AsOfMapper                    # noqa: E402
from core.commodity_brain import CommodityHeuristicPolicy  # noqa: E402
from nightly_forge_v9 import (trading_days, spot_token_for,  # noqa: E402
                              _shaped_barriers, _hold_seconds,
                              round_trip_costs, _kelly_budget)
from simulation.replay_real_day import load_day            # noqa: E402
from simulation.scenario_engine import N                   # noqa: E402

config.setup_logging("commodity_forge")
import logging                                            # noqa: E402
log = logging.getLogger("commodity_forge")

_LEGS = ["atm_ce", "atm_pe", "otm_ce", "otm_pe"]


def _kaufman_er(path: deque) -> float:
    """Signed Kaufman efficiency ratio of the recent spot path (same construct
    the equity signal path uses as tape evidence)."""
    if len(path) < 30:
        return 0.0
    a = np.asarray(path, float)
    net = a[-1] - a[0]
    churn = float(np.sum(np.abs(np.diff(a))))
    return float(net / churn) if churn > 0 else 0.0


def gen_samples(con, day: str):
    """One day, ALL harvested commodities, brain-identical signal generation.
    Returns perday-entry (X, Y, W) exactly as meta_gbm.fit_gbm expects."""
    commodities = [c for c in getattr(config, "HARVEST_COMMODITIES", [])
                   if spot_token_for(con, day, c)]
    if not commodities:
        return [], [], []
    loaded = load_day(con, day, commodities[0])
    if not loaded:
        return [], [], []
    _stok, by_sec, ti, bidA, askA = loaded
    import datetime as dt
    mapper = AsOfMapper(dt.date.fromisoformat(day))
    pol = CommodityHeuristicPolicy()
    sb = {c: StateBuilder() for c in commodities}
    spot_tok = {c: spot_token_for(con, day, c) for c in commodities}
    spot_hist = {c: deque(maxlen=600) for c in commodities}
    last_try = {c: -1e9 for c in commodities}
    chain_cache: dict = {}
    budget = _kelly_budget(config.FORGE_EVAL_CAPITAL)
    conv_bar = float(getattr(config, "COMMODITY_ENTRY_CONVICTION", 0.72))
    cool = float(getattr(config, "COMMODITY_FORGE_COOLDOWN_S", 180))
    F = config.FEATURES_PER_NODE

    X, Y, spans = [], [], []
    for t in sorted(by_sec):
        snaps = by_sec[t]
        for c in commodities:
            sp = snaps.get(spot_tok[c])
            if not sp or not sp.get("ltp"):
                continue
            spot = float(sp["ltp"])
            spot_hist[c].append(spot)
            ch = chain_cache.get(c)
            if ch is None or abs(spot - ch["atm"]) > ch["step"]:
                ch = mapper.chain(c, spot)
                if not ch or len(ch.get("legs", {})) < 2:
                    continue
                chain_cache[c] = ch
            dte, T_ = float(ch["dte"]), float(ch["T"])
            # nodes: spot + the 4 chain legs via the live feature path
            block = np.zeros((5, F), np.float32)
            block[0] = sb[c].leg_features(f"{c}:SPOT", sp, index=c,
                                          expiry=ch["expiry"], strike=0.0,
                                          opt_type="SPOT", spot=spot,
                                          T_years=T_, dte=dte,
                                          is_weekly=False, ts=float(t))
            legs_live = 0
            for j, leg in enumerate(_LEGS, start=1):
                info = ch["legs"].get(leg)
                s2 = snaps.get(info["token"]) if info else None
                if not s2:
                    continue
                block[j] = sb[c].leg_features(
                    f"{c}:{leg}", s2, index=c, expiry=ch["expiry"],
                    strike=float(info["strike"]),
                    opt_type="CE" if leg.endswith("ce") else "PE",
                    spot=spot, T_years=T_, dte=dte, is_weekly=False,
                    ts=float(t))
                legs_live += 1
            if legs_live < 2:
                continue
            sig = pol.predict({c: block}).get(c)
            if sig is None or abs(sig) < conv_bar:
                continue
            if t - last_try[c] < cool:
                continue
            d = "CE" if sig > 0 else "PE"
            # affordability walk, ASK entry — same as the equity sampler
            pick = None
            for r in mapper.hierarchy(c, spot, d):
                k = ti.get(r["token"])
                if k is None:
                    continue
                a_ = askA[k, t]
                if np.isnan(a_) or a_ <= 0:
                    continue
                if a_ * r["lot"] <= budget:
                    pick = (k, float(a_), int(r["lot"]), float(r["strike"]))
                    break
            if pick is None:
                continue
            last_try[c] = t
            k, e, lot, Kst = pick
            horizon = _hold_seconds(dte)
            mins_left = max((N - t) / 60.0, 1.0)
            if spot > 0 and Kst > 0 and T_ > 0 and e > 0:
                try:
                    tp, sl = _shaped_barriers(e, spot, Kst, T_, mins_left,
                                              d == "CE")
                    tp, sl = float(tp), float(sl)
                except Exception:                              # noqa: BLE001
                    tp = e * (1 + config.BASE_TP_PCT)
                    sl = e * (1 - config.BASE_SL_PCT)
            else:
                tp = e * (1 + config.BASE_TP_PCT)
                sl = e * (1 - config.BASE_SL_PCT)
            seg = bidA[k, t + 1:t + 1 + horizon]
            if seg.size == 0 or np.all(np.isnan(seg)):
                continue
            itp = int(np.argmax(seg >= tp)) if np.any(seg >= tp) else None
            isl = int(np.argmax(seg <= sl)) if np.any(seg <= sl) else None
            if itp is not None and (isl is None or itp < isl):
                exitp, off = float(tp), itp
            elif isl is not None:
                exitp, off = float(sl), isl
            else:
                valid = np.nonzero(~np.isnan(seg))[0]
                exitp, off = float(seg[valid[-1]]), int(valid[-1])
            pnl = (exitp - e) * lot - round_trip_costs(e * lot, exitp * lot)
            er = _kaufman_er(spot_hist[c])
            h = list(spot_hist[c])
            f30 = (h[-1] / h[-31] - 1.0) if len(h) > 31 and h[-31] else 0.0
            x = np.concatenate([block[0], block[1], block[2],
                                [t / N, er,
                                 math.copysign(min(abs(f30) * 100, 3), f30)
                                 if f30 else 0.0,
                                 1.0 if d == "CE" else -1.0]]).astype(np.float32)
            X.append(x)
            Y.append(1.0 if pnl > 0 else 0.0)
            spans.append((c, t, t + off + 1))
    # AFML uniqueness weights, per commodity (same as equity)
    W = np.ones(len(X), np.float32)
    for c in set(s[0] for s in spans):
        rows = [j for j, (c2, _, _) in enumerate(spans) if c2 == c]
        cvec = np.zeros(N + 1, np.int32)
        for j in rows:
            _, a, b = spans[j]
            cvec[a:min(b, N)] += 1
        for j in rows:
            _, a, b = spans[j]
            seg = cvec[a:min(b, N)]
            if seg.size:
                W[j] = float(np.mean(1.0 / np.maximum(seg, 1)))
    return X, Y, list(W)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=0)
    args = ap.parse_args()
    con = sqlite3.connect(config.DB_PATH)
    try:
        days = trading_days(con)
    except Exception as e:                                     # noqa: BLE001
        log.info("no vault yet (%s) — keep harvesting", e)
        return
    if args.days > 0:
        days = days[-args.days:]
    min_train = int(getattr(config, "COMMODITY_META_MIN_TRAIN", 300))
    perday, n = [], 0
    for day in days:
        try:
            x, y, w = gen_samples(con, day)
        except Exception as e:                                 # noqa: BLE001
            log.warning("  %s: sample gen failed (%s) — skipped", day, e)
            x, y, w = [], [], []
        perday.append((day, x, y, w))
        n += len(x)
        if x:
            log.info("  %s: %d commodity signals (mean uniq %.3f)",
                     day, len(x), float(np.mean(w)))
    log.info("commodity forge: %d labeled signals over %d day(s) "
             "(gate %d)", n, len(days), min_train)
    if n < min_train:
        log.info("below the training gate — the commodity brain stays "
                 "heuristic-only. Keep harvesting.")
        return
    from core import meta_gbm as MG
    out = MG.fit_gbm(perday, min_train)
    if out is None:
        log.warning("fit_gbm returned None (lightgbm absent or CV too thin) "
                    "— NO model written; brain stays heuristic-only")
        return
    path = config.MODEL_DIR / "commodity_meta.json"
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(out))
    tmp.replace(path)
    log.info("COMMODITY META promoted: %d signals | OOF Brier %.4f→%.4f | "
             "holdout acc %.1f%% | %s → %s", out["n"], out["oof_brier_raw"],
             out["oof_brier_cal"], 100 * out["holdout_acc"], out["holdout"],
             path.name)


if __name__ == "__main__":
    main()